server:
  port: 8765

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: application-registration
          uri: lb://APPLICATION-REGISTRATION-SERVICE
          predicates:
            - Path=/applications/**, /get/**, /getAll/**, /update/**, /delete/**

        - id: data-collection
          uri: lb://DATA-COLLECTION-SERVICE
          predicates:
            - Path=/api/data-collection/**

        - id: eligibility-determination
          uri: lb://ELIGIBILITY-DETERMINATION-SERVICE
          predicates:
            - Path=/api/eligibility/**

        - id: benefit-issuance
          uri: lb://BENEFIT-ISSUANCE-SERVICE
          predicates:
            - Path=/benefits/**

        - id: correspondence
          uri: lb://CORRESPONDENCE-SERVICE
          predicates:
            - Path=/correspondence/**
jwt:
  secret: HISProjectSecretKeyForJWTTokenGenerationAndValidation2024

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka