server:
  port: 9096

spring:
  application:
    name: BENEFIT-ISSUANCE-SERVICE

  datasource:
    url: jdbc:mysql://mysql:3306/his_project
    username: root
    password: Ramcharan8@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka